### ISSUE TITLE
Handle multiple templates with same identifier

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero-word-add-in#25]
We need to restrict user to upload templates with unique identifier. This will help us re-attaching the listeners more efficiently.

To explain this more briefly, I will elaborate on how the listeners get attached in the first place.

1. Whenever a template is added for the first time, the template identifier is stored, as [`CustomXMPart`](https://docs.microsoft.com/en-us/javascript/api/office/office.customxmlpart?view=common-js), in the document which looks something like this:
    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <templates xmlns="https://accordproject.org/">
      <template xmlns="acceptance-of-delivery@0.14.0" />
      ...
    </templates>
    ```
    > If `acceptance-of-delivery@0.14.0` is added two times, the xml **will not** show two occurrences of `<template xmlns="acceptance-of-delivery@0.14.0" />`. (This is purposely added because I thought it may unnecessarily populate the XML)

2. When the Add-in is opened, it iterates over this `XML` and fetches the corresponding compiled archives and list down the variables they contain.
    ```js
    ["Shipper1", "Receiver1", "Deliverable1", "Receiver2", "Shipper2", "Deliverable2", "Receiver3", "BusinessDays1", "Deliverable3", "Shipper3", "Deliverable4", "Deliverable5", "Shipper4", "Attachment1"]
    ```

3.  A function then iterates over this list and add listener to the content control **if** it is also present in the above list.

The problem here is that we don't have a way to enumerate the times a template exists in the document. But I suggest three approaches for this:

1. Remove the check for uniqueness in the XML.
2. Generate the XML something like this:
    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <templates xmlns="https://accordproject.org/">
      <template xmlns="acceptance-of-delivery@0.14.0">3</template>
      ...
    </templates>
    ```
    > not sure if one will be able to query the XML properly.
3. Add a function to restrict user to add templates with unique identifier.

**Comment by jolanglinais** [comment]
It seems like it would make sense to me to enforce unique identifiers per template (option 3). @DianaLease, @jeromesimeon thoughts?

**Comment by algomaster99** [comment]
Yeah, the third option makes the most sense to me as well but I still wanted opinions.

**Comment by DianaLease** [comment]
In the custom XML, can we use a uuid that we store as the `name` property on the clause as the identifier instead of using the template uri? Since we want the custom xml to point to an instance of the template, correct?

**Comment by algomaster99** [comment]
@DianaLease we can do that. From CustomXML, we can get the `uuid` and use it to access content controls (full clauses in this case) via `tag`. The same content control will have the `title` property too which will store the template identifier and therefore, we will be able to fetch the compiled archive.

**Comment by K-Kumar-01** [comment]
@algomaster99 @irmerk @DianaLease

https://user-images.githubusercontent.com/59891164/114442978-cc77fc00-9bea-11eb-95d3-5595b7a7eaa9.mp4

I tried some code and now when we enter more than one same template, the effect of one template is not displayed on other as seen in the above.
As far as I am understanding, we wanted this feature. So should I make a draft PR regarding this?

**Comment by algomaster99** [comment]
This looks really nice! But in my opinion, I think it would be better to follow the 3rd approach i.e. - 'Add a function to restrict the user to add templates with a unique identifier.'. The point is that each contract should exist only once in a document and we would want to avoid repetition. Not exactly sure but maybe @DianaLease and @irmerk can elaborate on this.

**Comment by K-Kumar-01** [comment]
@algomaster99 @irmerk @DianaLease 
I have created a PR following the 3rd approach. Let me know if there are any changes required.
