### ISSUE TITLE
Docstrings are missing from the entire project

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero-word-add-in#37]
Docstrings should be added for all the functions in the add-in. This will allow us to prevent issues such as https://github.com/accordproject/cicero-word-add-in/issues/35. Moreover, adding docstrings should be enforced by using some eslint configuration.

**Comment by K-Kumar-01** [comment]
@algomaster99 
I think I will be able to tackle this, so is it fine if I go ahead with this issue?

**Comment by algomaster99** [comment]
Sure, go ahead!

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have created a PR for the issue. Let me know if there are any changes required.
