### ISSUE TITLE
Quotation marks in variable values

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero-word-add-in#39]
# Discussion 🗣

Currently in the add-in, when we insert a template the variable values which are string have quotes wrapped around them which are included in their value. This quote is an extra one that gets inserted when the template is converted into ciceromark.
Since this is unintentional, it would be good to remove these extra quotation marks when the variable value is inserted into the document via an add-in.

## Context

![Screenshot (33)](https://user-images.githubusercontent.com/59891164/113506923-3a765080-9565-11eb-8f5e-71aafeacb86d.png)
In the given image, I have outlined some of the variables which have extra quotes wrapped around them

### Would you like to work on this?
Yes, I would like to work on this one.
EDIT: I have already found a solution for this.

**Comment by jolanglinais** [comment]
@algomaster99 any thoughts on this? I don't recall why we needed quotation marks.

**Comment by algomaster99** [comment]
@K-Kumar-01 thanks for raising the issue.

I think the extra `""` are not put intentionally. They come directly from CiceroMark JSON of a sample text of a particular template. As far as I remember the values in the CiceroMark JSON were stored like this - `{name: "\"Party A\""}`.

I might be wrong though. Could you please confirm, @irmerk @K-Kumar-01 ?

**Comment by jolanglinais** [comment]
That sounds right. Probably something we didn't want to bother with last summer at the time.

**Comment by K-Kumar-01** [comment]
@algomaster99 
The values in JSON mark are as follows 
```js
$class: "org.accordproject.ciceromark.Variable"
elementType: "org.accordproject.organization.Organization"
identifiedBy: "identifier"
name: "shipper"
value: ""Party A""
```
So yeah basically what you are saying is right. 
However, in [contract-editor](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor) (web-components), the values do not contain the `""` wrapped around them. This led me to think that these might be unintentional when it gets converted to CiceroMark JSON.
Maybe you or @irmerk can explain better to me about this

**Comment by nishihere19** [comment]
I had a similar doubt, when the user edits a variable, it allows them to remove the double-quotes. Was it intentional or we want to preserve the double-quotes as well?

**Comment by K-Kumar-01** [comment]
@algomaster99 @irmerk 
Should I make a PR for the issue.

**Comment by algomaster99** [comment]
@K-Kumar-01 you can go ahead. The contract editor probably strips the `""` out of the variable value so do how its done in there. Also, make sure roundtripping is not broken because of this.

**Comment by K-Kumar-01** [comment]
@algomaster99 
In contract editor, there is no extra `""` in the values.
![Screenshot (63)](https://user-images.githubusercontent.com/59891164/117117836-9ffc6d80-adad-11eb-8219-144211826f68.png)
So I don't think we can use its implementation for the same. 
Though I have found a solution for which I make a PR ASAP.

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have made a PR for the issue. Let me know if there are any changes required.
