### ISSUE TITLE
Integrating Pre- commit hook

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero-word-add-in#46]
# Feature Request 🛍️

Pre-commit hooks should be integrated into the project to prevent the push of bad code( not linted properly and others).

## Context

Currently, if someone pushes the code into the repo which is not properly linted there is no check on it. This can cause inconsistencies in code. This feature would prevent this from happening.

## Detailed Description

Some info regarding the [pre-commit hooks](https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e)

**Comment by Aniruddha-Shriwant** [comment]
Can I take it up?

**Comment by K-Kumar-01** [comment]
@Aniruddha-Shriwant 
Actually I am gonna work upon this. I think i forgot to write `would you like to work on this`😅

**Comment by Aniruddha-Shriwant** [comment]
>  I think i forgot to write would you like to work on this😅

Yeah that's why I asked if I can take this up 😅

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have made a PR for the issue. Let me know if there are any changes required.
