### ISSUE TITLE
Type: Regression [eslint commands]

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [accordproject/cicero-word-add-in#47]
# Bug Report 🐛

Single Quotes in eslint's command pattern causes error while linting

https://github.com/accordproject/cicero-word-add-in/blob/2caf0f5abf6b05e0ff1cc6d54da355e45147540c/package.json#L19-L20

> Why are these quotes needed?

Originally posted by @algomaster99 [in this comment](https://github.com/accordproject/cicero-word-add-in/pull/38/files#r611104218) 

## Expected Behavior

Running the `npm run lint` or `npm run lint:fix` commands, eslint should work properly and/or fix any linting errors if present.
## Current Behavior

As single quotes are added to the eslint's command pattern it causes the following error:
```
PS D:\Github\cicero-word-add-in> npm run lint:fix

> cicero-word-add-in@0.0.1 lint:fix
> eslint '**/*.{js,jsx}' --fix     


Oops! Something went wrong! :(
ESLint: 7.1.0

No files matching the pattern "'**/*.{js,jsx}'" were found.
Please check for typing mistakes in the pattern.

PS D:\Github\cicero-word-add-in> 
``` 
As you can see the eslint was unable to find the files due to a typo in the pattern.

## Possible Solution

I had removed the quotes and it works fine, for example I had intentionally created some error to see if eslint works fine or not
```
PS D:\Github\cicero-word-add-in> npm run lint:fix

> cicero-word-add-in@0.0.1 lint:fix
> eslint **/*.{js,jsx} --fix       


D:\Github\cicero-word-add-in\src\components\TemplateLibrary\index.js
  17:14  error  Parsing error: Const declarations require an initialization value

  15 | const XML_HEADER = '<?xml version="1.0" encoding="utf-8" ?>';
  16 |
> 17 | const example;
     |              ^
  18 |
  19 | /**
  20 |  * Template library Renderer.

✖ 1 problem (1 error, 0 warnings)

PS D:\Github\cicero-word-add-in> 
``` 
I can create a PR for this if needed :)

**Comment by Aniruddha-Shriwant** [comment]
Although @K-Kumar-01 had pointed out to [this](https://github.com/eslint/eslint/issues/10880) issue in [this](https://github.com/accordproject/cicero-word-add-in/pull/38/files#r611138367) comment, I think as that issue was ~3years old, the single quotes in the pattern is not needed now as that might be resolved now.

**Comment by K-Kumar-01** [comment]
@Aniruddha-Shriwant 
It still gives the following error if quotes are not put.
```js
> eslint **/*.{js,jsx}


Oops! Something went wrong! :(

ESLint: 7.1.0

No files matching the pattern "node_modules/asn1.js" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cicero-word-add-in@0.0.1 lint: `eslint **/*.{js,jsx}`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cicero-word-add-in@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kusha\AppData\Roaming\npm-cache\_logs\2021-04-15T08_04_04_624Z-debug.log
```

However, when quotes are put no error is displayed.

**Comment by Aniruddha-Shriwant** [comment]
That's Strange!
Closing this temporary let #44 get merged and then let's see the eslint output

**Comment by Aniruddha-Shriwant** [comment]
Reopening by [this comment](https://github.com/accordproject/cicero-word-add-in/pull/49#discussion_r618751435)

**Comment by K-Kumar-01** [comment]
@algomaster99 @Aniruddha-Shriwant 
I am facing an error in running the command.
![Screenshot (65)](https://user-images.githubusercontent.com/59891164/117975576-6fd44200-b34c-11eb-84a6-e0f6e986831e.png)

I think we need to revert back.

**Comment by algomaster99** [comment]
> I think we need to revert back.

I don't think so. Seems more like a [Windows issue](https://link.medium.com/HLT4o3Oncgb). I can suggest one fix.
1. Install WSL.
2. Link its bash terminal to the terminal inside VSCode.

**Comment by Aniruddha-Shriwant** [comment]
Well @K-Kumar-01 That's weird
I was able to run those commands successfully

On Gitpod : 
![image](https://user-images.githubusercontent.com/58624108/117994848-74095b00-b35e-11eb-87b8-f4f257c61d08.png)

On Windows10 :
![image](https://user-images.githubusercontent.com/58624108/117994898-808db380-b35e-11eb-8fc8-a9dfbbfe018c.png)

On Ubuntu :
![image](https://user-images.githubusercontent.com/58624108/117997560-b2077e80-b360-11eb-8475-04bd58eacd22.png)


> I don't think so. Seems more like a Windows issue.

@algomaster99 I agreed, because I had tried to run it on a different OS it works neatly.
