### ISSUE TITLE
Adding `CONTRIBUTNG.md` and `DEVELOPERS.md` files

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [accordproject/cicero-word-add-in#50]
# Discussion 🗣
Adding `CONTRIBUTNG.md` and `DEVELOPERS.md` files in the repo similar to other Accord Project's repositories
These files will point out to techdocs [CONTRIBUTNG.md](https://github.com/accordproject/techdocs/blob/master/CONTRIBUTING.md) and [DEVELOPERS.md](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md) respectively

Also, we can add `Cicero-word-add-in` specific information in them similar to what it is done in Cicero's [CONTRIBUTNG.md](https://github.com/accordproject/cicero/blob/master/CONTRIBUTING.md#cicero-specific-information)

I would like to create a PR for this if needed

**Comment by algomaster99** [comment]
Yeah, you can go for it.
