### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero-word-add-in#53]
# Bug Report 🐛

Currently, the dependencies installed are old. As a result, there occurs an error when inserting the template. 
![Screenshot (60)](https://user-images.githubusercontent.com/59891164/116906148-864c1080-ac5d-11eb-835b-fe8186c56cde.png)

## Expected Behavior

The template should be inserted.

## Current Behavior

The above error shows

## Possible Solution

Updating the major dependencies of the project.

### Desktop
 - OS: Windows 10
 - Text Editor: MS-Word
 - Version: OS-Build: 19042.867, Word-Office 365 v2103

#### would you like to work on the issue?
YES

**Comment by Aniruddha-Shriwant** [comment]
Yeah I too just faced this error, this is caused by Cicero's version  
Updating Cicero's version by `npm install @accordproject/cicero-core@latest` solves this error! I had tried this locally

**Comment by K-Kumar-01** [comment]
@Aniruddha-Shriwant 
Yeah I am making a PR for this right now.

**Comment by K-Kumar-01** [comment]
@algomaster99 @irmerk 
I have made a PR for the issue. Let me know if there are any changes required.
