### ISSUE TITLE
Debug Addin: New Method and Documentation

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero-word-add-in#63]
# Feature Request 🛍️

Due to an update of the  Edge Chromium, the current debug method for add-in is facing issues. Basically, the add-in reloads after 5 seconds if the debugger is attached to it. A new debug method can be used for such cases.

## Use Case

Debugging is an important part of development so the debugger should work.

## Possible Solution

Using [this](https://github.com/OfficeDev/office-js/issues/1852#issuecomment-840177792) we can implement a solution.

## Context

Whenever an update occurs, there might occur similar changes which lead to breaking the working of debugging the add-in. In such cases, one can opt the other method to debug and continue the work.

## Detailed Description

A `launch.json` file would need to be created along with some documentation changes for the same describing its working.

### Would you like to work on the issue??
Yes

**Comment by algomaster99** [comment]
If you and @Aniruddha-Shriwant are facing this issue, feel free to work on this. I am not facing it yet. That could be probably because I haven't updated my edge.

**Comment by K-Kumar-01** [comment]
@algomaster99
I have created a PR. Let me know if there are any changes required.
